services:
  postgres:
    build:
      dockerfile: Dockerfile.postgres
    container_name: postgres
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
      - postgres-bash-history:/home
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      private:

  rails:
    build:
      dockerfile: Dockerfile.rails
    container_name: rails
    volumes:
      - ./rails/:/app
      - gems:/var/lib/gems
      - rails-bash-history:/commandhistory
    ports:
      - ${RAILS_PORT}:3000
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: postgres
    networks:
      private:
    command: tail -F anything
    # command: rails server -b 0.0.0.0

volumes:
  postgres-bash-history:
  rails-bash-history:
  postgres-data:
  gems:


networks:
  private:
    driver: bridge
