FROM postgres:16.4-bullseye

RUN apt update
RUN apt install -y \
  vim

# Setup command history
RUN SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/root/.bash_history" \
  && mkdir "commandhistory" \
  && mkdir "/commandhistory/root" \  
  && echo "$SNIPPET" >> "/root/.bashrc"