source "https://rubygems.org"

gem "rails", "~> 7.2.1"
gem "sprockets-rails"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "pg"
gem "bootsnap", require: false
gem "byebug"
gem "awesome_print"
gem "activerecord-import"
gem "rack-cors"
gem 'grape'
gem 'grape-swagger'
gem 'grape-swagger-rails'

group :development, :test do
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end
